const rules = [
    {left: ["S"],                                                       right: ["<table>", "A", "</table>"],                                             comment: "start"},
    {left: ["A"],                                                       right: ["<tbody>", "B", "</tbody>"],                                             comment: "without header"},
    {left: ["A"],                                                       right: ["<thead>", "H", "</thead>"],                                             comment: "with header"},
    {left: ["H", "</thead>"],                                           right: ["</thead>", "<tbody>", "B", "</tbody>"]                                 },
    {left: ["H"],                                                       right: ["<tr>", "</tr>", "E"]                                                   },
    {left: ["E"],                                                       right: ["<tr>", "</tr>", "E"]                                                   },
    {left: ["E", "</thead>"],                                           right: ["</thead>", "<tbody>", "E", "</tbody>"]                                 } ,
    {left: ["E", "</tbody>"],                                           right: ["</tbody>", "<tfoot>", "E", "</tfoot>"]                                 },
    {left: ["E", "</tfoot>"],                                           right: ["</tfoot>"]                                                             },
    {left: ["E", "</tbody>"],                                           right: ["</tbody>"]                                                             },
    {left: ["H"],                                                       right: ["<tr>","C1", "<th>","</th>", "J1", "</tr>"]                             },
    {left: ["<tr>", "C1"],                                              right: ["<tr>", "C1", "<th>", "</th>"]                                          },
    {left: ["C1", "<th>", "</th>"],                                     right: ["<th>", "</th>", "C1", "C1"]                                            },
    {left: ["C1", "C1","J1", "</tr>"],                                  right: ["C1", "C1", "J2", "</tr>", "<tr>", "J1", "</tr>"]                       },
    {left: ["C1", "C1", "J2", "</tr>", "<tr>"],                         right: ["J2", "</tr>", "<tr>", "<th>", "</th>"]                                 },
    {left: ["</th>", "</tr>", "J2", "<tr>"],                            right: ["</th>", "</tr>", "<tr>", "J3"]                                         },
    {left: ["J3", "<th>", "</th>"],                                     right: ["<th>", "</th>", "C1", "C1"]                                            },
    {left: ["C1", "C1", "J1", "</tr>", "</thead>"],                     right: ["C1", "C1", "J4", "</tr>", "</thead>", "<tbody>", "F1", "</tbody>"]     },
    {left: ["C1", "C1", "J4", "</tr>", "</thead>", "<tbody>"],          right: ["C1", "C1", "J5", "</tr>", "</thead>", "<tbody>", "<tr>", "</tr>"]      },
    {left: ["C1", "C1", "J5", "</tr>", "<thead>", "<tbody>", "<tr>"],   right: ["J5", "</tr>", "</thead>", "<tbody>", "<tr>", "<td>", "</td>"]          },
    {left: ["</th>", "J5", "</tr>", "</thead>", "<tbody>", "<tr>"],     right: ["</th>", "</tr>", "</thead>", "<tbody>", "<tr>", "C2"]                  },
    {left: ["C2", "<td>", "</td>"],                                     right: ["<td>", "</td>", "C2", "C2"]                                            },
    {left: ["C2", "C2", "</tr>", "F1"],                                 right: ["C2", "C2", "</tr>", "F2", "<tr>", "</tr>", "F1"]                       },
    {left: ["C2", "C2", "</tr>", "F2", "<tr>"],                         right: ["</tr>", "F2", "<tr>", "<td>", "</td>"]                                 },
    {left: ["</td>", "</tr>", "F2", "<tr>"],                            right: ["</td>", "</tr>", "<tr>", "C2"]                                         },
    {left: ["C2", "C2", "</tr>", "F1", "</tbody>"],                     right: ["C2", "C2", "</tr>", "W1", "</tbody>"]                                  },
    {left: ["C2", "C2", "</tr>", "W1", "</tbody>"],                     right: ["</tr>", "W1", "</tbody>"]                                              },
    {left: ["</td>", "</tr>", "W1", "</tbody>"],                        right: ["</td>", "</tr>", "</tbody>"]                                           },
    {left: ["</td>", "</tr>", "W1", "</tbody>"],                        right: ["</td>", "</tr>", "</tbody>", "<tfoot>", "</tfoot>"]                    },
    {left: ["C2", "C2", "</tr>", "F1", "</tbody>"],                     right: ["C2", "C2", "</tr>", "F4", "</tbody>", "<tfoot>", "F1", "</tfoot>"]     },
    {left: ["C2", "C2", "</tr>", "F4", "</tbody>", "<tfoot>"],          right: ["C2", "C2", "</tr>", "F5", "</tbody>", "<tfoot>", "<tr>", "</tr>"]      },
    {left: ["C2", "C2", "</tr>", "F5", "</tbody>", "<tfoot>", "<tr>"],  right: ["</tr>", "F5", "</tbody>", "<tfoot>", "<tr>", "<td>", "</td>"]          },
    {left: ["</td>", "</tr>", "F5", "</tbody>", "<tfoot>", "<tr>"],     right: ["</td>", "</tr>", "</tbody>", "<tfoot>", "<tr>", "C2"]                  },
    {left: ["C2", "C2", "</tr>", "F1", "</tfoot>"],                     right: ["C2", "C2", "</tr>", "F6", "</tfoot>"]                                  },
    {left: ["C2", "C2", "</tr>", "F6", "</tfoot>"],                     right: ["</tr>", "F6", "</tfoot>"]                                              },
    {left: ["</td>", "</tr>", "F6", "</tfoot>"],                        right: ["</td>", "</tr>", "</tfoot>"]                                           },
    {left: ["C2", "C2", "</tr>", "F4", "</tbody>", "<tfoot>"],          right: ["C2", "C2", "</tr>", "F3", "</tbody>", "<tfoot>"]                       },
    {left: ["F3", "</tbody>", "<tfoot>", "F1"],                         right: ["F7", "<tbody>", "<tfoot>"]                                             },
    {left: ["C2", "C2", "</tr>", "F7", "</tbody>"],                     right: ["</tr>", "F7", "</tbody>"]                                              },
    {left: ["</td>", "</tr>", "F7", "</tbody>"],                        right: ["</td>", "</tr>", "</tbody>"]                                           },
    {left: ["C1", "C1", "J1", "</tr>", "</thead>"],                     right: ["C1", "C1", "J6", "</tr>", "</thead>", "F8"]                            },
    {left: ["C1", "C1", "J6", "</tr>", "</thead>", "F8"],               right: ["J6", "</tr>", "</thead>", "F8", "C3", "C3"]                            },
    {left: ["</th>", "J6", "</tr>", "</thead>", "F8"],                  right: ["</th>", "</tr>", "<thead>", "J7", "F8"]                                },
    {left: ["J7", "F8"],                                                right: ["F8", "J8"]                                                             },
    {left: ["J8", "C3", "C3"],                                          right: ["J9", "J8"]                                                             },
    {left: ["F8", "J9"],                                                right: ["F8"]                                                                   },
    {left: ["F8", "J8", "</table>"],                                    right: ["<tbody>", "</tbody>", "<tfoot>", "</tfoot>", "</table>"]               },
    {left: ["F8", "J8", "</table>"],                                    right: ["<tbody>","</tbody>", "</table>"]                                       },
    {left: ["J7", "F8", "C3", "C3"],                                    right: ["<tbody>", "</tbody>", "J10", "<tfoot>", "<tr>", "</tr>", "</tfoot>", "F9", "C3", "C3"]},
    {left: ["</tr>", "</tfoot>", "F9", "C3", "C3"],                     right: ["<td>", "</td>", "</tr>", "</tfoot>", "F9"]                             },
    {left: ["</tr>", "</tfoot>", "F9", "</table>"],                     right: ["</tr>", "F1", "</tfoot>", "<table>"]                                   },
    {left: ["</tbody>", "J10", "<tfoot>", "<tr>"],                      right: ["</tbody>", "<tfoot>", "<tr>", "C2"]                                    },
    {left: ["B"],                                                       right: ["<tr>", "</tr>", "E"],                                                   comment:"rows without cells"},
    {left: ["B"],                                                       right: ["<tr>", "C4", "</tr>", "F1"],                                            comment:"rows with cells"},
    {left: ["<tr>", "C4"],                                              right: ["<tr>", "C4", "<td>", "</td>"]                                          },
    {left: ["C4", "<td>", "</td>"],                                     right: ["<td>", "</td>", "C2", "C2"]                                            },
    {left: ["B", "<tbody>"],                                            right: ["</tbody>", "M"]                                                        },
    {left: ["M"],                                                       right: ["<tfoot>", "</tfoot>"]                                                  },
    {left: ["B", "</tbody>"],                                           right: ["</tbody>"]                                                             },
    {left: ["B", "</tbody>"],                                           right: ["</tbody>", "V"]                                                        },
    {left: ["V"],                                                       right: ["</tbody>", "<tfoot>", "<tr>", "C4", "</tr>", "F1", "</tfoot>"]         },
    {left: ["V"],                                                       right: ["</tbody>", "<tfoot>", "E", "</tfoot>"]                                 }
]

export default rules;